spring:
  cloud:
    config:
      server:
        git:
          uri:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
  security:
    user:
      password: test

server:
  port: 10001
